name: CI

on:
  push:
    branches: [ '**' ]
    tags: [v*]
  pull_request:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Run tests
        run: ./millw _.test